export type SmartSocketReadingPayload = SmartSocket

export type SmartSocketReading = {
    idempotency_key: string,
    device_id: bigint,
    current: number,
    energy: number,
    energy_month: number,
    energy_today: number,
    energy_yesterday: number,
    linkquality: number,
    outlet_control_protect: boolean,
    enable_max_voltage: string,
    enable_min_current: string,
    enable_min_power: string,
    enable_min_voltage: string,
    max_current: number,
    max_power: number,
    max_voltage: number,
    min_current: number,
    min_power: number,
    min_voltage: number,
    power: number,
    power_on_behavior: string,
    voltage: number,
    received_at: string,
    label: string,

}
export type SmartSocket = {
    idempotency_key: string,
    device_id: bigint,
    current: number,
    energy: number,
    energy_month: number,
    energy_today: number,
    energy_yesterday: number,
    linkquality: number,
    outlet_control_protect: boolean,
    power: number,
    power_on_behavior: string,
    voltage: number,
    received_at: Date,
    overload_protection: {
        enable_max_voltage: string,
        enable_min_current: string,
        enable_min_power: string,
        enable_min_voltage: string,
        max_current: number,
        max_power: number,
        max_voltage: number,
        min_current: number,
        min_power: number,
        min_voltage: number,
    }
    last_seen: string,
}